"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
import environ
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

IS_TESTING = "test" in sys.argv or "pytest" in sys.modules

env = environ.Env(
    DEBUG=(bool, False)
)

BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret
SECRET_KEY = env('SECRET_KEY')

ADMIN_REGISTRATION_PASSKEY = env('ADMIN_REGISTRATION_PASSKEY', default='').strip()
if not ADMIN_REGISTRATION_PASSKEY:
    raise ImproperlyConfigured(
        'ADMIN_REGISTRATION_PASSKEY must be configured with a non-empty secret.'
    )

PRIVACY_CONSENT_VERSION = "resident-v1"

# SECURITY WARNING: don't run with debug turned on in production
DEBUG = env('DEBUG')

ALLOWED_HOSTS = list(dict.fromkeys([
    *env.list('ALLOWED_HOSTS', default=['.onrender.com']),
    'localhost',
    '127.0.0.1',
]))

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Reverse-Proxy SSL Awareness (Render / Cloudflare Edge)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF Trusted Origins for Cross-Domain Web Portal & Admin
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'https://*.onrender.com',
    'https://*.vercel.app',
    'http://localhost:5173',
    'http://localhost:3000',
])

# Frontend Client URL for Authentication Links
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:5173')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'cloudinary',
    'gridy_auth',
    'gridy_services',
    'gridy_reports',
    'gridy_communications',
    'gridy_audit',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Leave WSGI_APPLICATION there as a fallback for standard HTTP
WSGI_APPLICATION = 'config.wsgi.application'

# Add ASGI application for WebSockets
ASGI_APPLICATION = 'config.asgi.application'

# Use the in-memory channel layer during tests.

if IS_TESTING:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }


import socket 

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default='sqlite:///db.sqlite3')
}



# 1. Connection pooling for serverless PostgreSQL (drops idle re-negotiation)
DATABASES['default']['CONN_MAX_AGE'] = 60
DATABASES['default']['CONN_HEALTH_CHECKS'] = True

# 2. Force IPv4 connection to prevent Linux 'Network is unreachable' on IPv6
db_host = DATABASES['default'].get('HOST')
if db_host and not db_host.startswith('/') and db_host != 'localhost':
    try:
        DATABASES['default'].setdefault('OPTIONS', {})['hostaddr'] = socket.gethostbyname(db_host)
    except Exception:
        pass
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost',
    'http://127.0.0.1',
    'http://localhost:3000', 
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
])

if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
    ]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # 1. Global Pagination (Prevents OOM Crashes from massive queries)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,

    # Basic application-level request budgets. These are not a security
    # boundary against brute-force or denial-of-service attacks.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth_login': '10/minute',
        'auth_register': '20/hour',
        'auth_admin_register': '5/hour',
        'barangay_application': '5/hour',
        'password_reset_request': '5/hour',
        'password_reset_confirm': '10/hour',
    }
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTH_USER_MODEL = 'gridy_auth.User'

CLOUDINARY_CLOUD_NAME = env('CLOUDINARY_CLOUD_NAME', default='')
CLOUDINARY_API_KEY = env('CLOUDINARY_API_KEY', default='')
CLOUDINARY_API_SECRET = env('CLOUDINARY_API_SECRET', default='')

if not DEBUG and not IS_TESTING:
    missing_cloudinary_settings = [
        name
        for name, value in (
            ('CLOUDINARY_CLOUD_NAME', CLOUDINARY_CLOUD_NAME),
            ('CLOUDINARY_API_KEY', CLOUDINARY_API_KEY),
            ('CLOUDINARY_API_SECRET', CLOUDINARY_API_SECRET),
        )
        if not value.strip()
    ]
    if missing_cloudinary_settings:
        raise ImproperlyConfigured(
            'Production media storage requires: '
            + ', '.join(missing_cloudinary_settings)
            + '.'
        )

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

if CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET:
    CLOUDINARY_STORAGE = { 
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
    }
    STORAGES = {
        "default": {
            "BACKEND": "config.private_media_storage.ResidentAwareCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }


FIREBASE_SERVICE_ACCOUNT_JSON_PATH = env('FIREBASE_SERVICE_ACCOUNT_JSON_PATH', default='')
if not FIREBASE_SERVICE_ACCOUNT_JSON_PATH:
    FIREBASE_SERVICE_ACCOUNT_JSON_PATH = str(BASE_DIR / 'firebase-admin-key.json')
elif not Path(FIREBASE_SERVICE_ACCOUNT_JSON_PATH).is_absolute():
    FIREBASE_SERVICE_ACCOUNT_JSON_PATH = str(BASE_DIR / FIREBASE_SERVICE_ACCOUNT_JSON_PATH)


SPECTACULAR_SETTINGS = {
    'TITLE': 'Gridy API',
    'DESCRIPTION': 'Barangay Information and Service Management System API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_PERMISSIOMNS': ['gridy_auth.permissions.IsBarangayOfficial'],
}

# Cache Settings (In-memory cache for session and throttling management)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Structured JSON Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'config.logging.JSONFormatter',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'gridy': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Email Configuration (SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='').strip()
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER).strip()

if not DEBUG and not IS_TESTING:
    missing_email_settings = [
        name
        for name, value in (
            ('EMAIL_HOST', EMAIL_HOST),
            ('EMAIL_HOST_USER', EMAIL_HOST_USER),
            ('EMAIL_HOST_PASSWORD', EMAIL_HOST_PASSWORD),
            ('DEFAULT_FROM_EMAIL', DEFAULT_FROM_EMAIL),
        )
        if not value.strip()
    ]
    if missing_email_settings:
        raise ImproperlyConfigured(
            'Production email delivery requires: '
            + ', '.join(missing_email_settings)
            + '.'
        )

    if (
        not FIREBASE_SERVICE_ACCOUNT_JSON_PATH
        or not Path(FIREBASE_SERVICE_ACCOUNT_JSON_PATH).is_file()
    ):
        raise ImproperlyConfigured(
            'Production push notifications require a valid '
            'FIREBASE_SERVICE_ACCOUNT_JSON_PATH.'
        )

    # Production Security Headers & Cookie Policies
    SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=True)
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)
    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

REFRESH_COOKIE_SAMESITE = env('REFRESH_COOKIE_SAMESITE', default='Strict')

SENTRY_DSN = env('SENTRY_DSN', default='').strip()
if SENTRY_DSN and not IS_TESTING:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=env.float('SENTRY_TRACES_SAMPLE_RATE', default=0.1),
            send_default_pii=False,
        )
    except Exception:
        pass

# Local tests default to SQLite; CI can select PostgreSQL for row-level tests.
if IS_TESTING:
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"

    if env.bool("GRIDY_TEST_USE_SQLITE", default=True):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': ':memory:',
            }
        }
