# Generated by Django 6.0.7 on 2026-08-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0003_refreshsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='purok',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
