# Generated by Django 6.0.7 on 2026-08-16 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0003_refreshsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='gridy_auth.resident'),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='purok',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
