# Generated by Django 6.0.7 on 2026-08-23 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0005_resident_guardian_resident_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RESIDENT', 'Resident'), ('DILG_ADMIN', 'DILG Admin')], default='RESIDENT', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='barangay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='gridy_auth.barangay'),
        ),
    ]
