# Generated by Django 6.0.7 on 2026-08-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0006_barangay_alter_user_role_user_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='captain_name',
            field=models.CharField(blank=True, help_text='Full name of the incumbent Punong Barangay', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='city_seal',
            field=models.ImageField(blank=True, null=True, upload_to='barangay_logos/'),
        ),
        migrations.AddField(
            model_name='barangay',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='barangay_logos/'),
        ),
        migrations.AddField(
            model_name='barangay',
            name='office_contact',
            field=models.CharField(blank=True, help_text='Office Address or Phone Number', max_length=255, null=True),
        ),
    ]
