# Generated by Django 6.0.7 on 2026-08-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0007_barangay_captain_name_barangay_city_seal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_alerts',
            field=models.BooleanField(default=True, help_text='Receive daily queue and request email reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_alerts',
            field=models.BooleanField(default=False, help_text='Receieve real-time FCM push notifications'),
        ),
    ]
