# Generated by Django 6.0.8 on 2026-09-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0008_user_email_alerts_user_push_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RESIDENT', 'Resident'), ('DILG_ADMIN', 'DILG Admin'), ('FIELD_OFFICIAL', 'Field Official')], default='RESIDENT', max_length=50),
        ),
    ]
