# Generated by Django 6.0.8 on 2026-09-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0010_alter_resident_purok'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='philsys_id_number',
            field=models.CharField(blank=True, help_text='PhilSys National ID Card Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='philsys_id_photo',
            field=models.ImageField(blank=True, help_text='Photo of National / PhilSys ID', null=True, upload_to='resident_ids/'),
        ),
        migrations.AddField(
            model_name='resident',
            name='secondary_id_photo',
            field=models.ImageField(blank=True, help_text='Optional secondary ID photo', null=True, upload_to='resident_ids/'),
        ),
        migrations.AddField(
            model_name='resident',
            name='secondary_id_type',
            field=models.CharField(blank=True, help_text="Optional secondary ID type (e.g. Passport, Driver's License, UMID, Postal ID)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='utility_billing_photo',
            field=models.ImageField(blank=True, help_text='Optional proof of billing photo', null=True, upload_to='resident_billings/'),
        ),
        migrations.AddField(
            model_name='resident',
            name='utility_billing_type',
            field=models.CharField(blank=True, help_text='Optional utility billing proof type (e.g. Electric/Meralco, Water, Internet)', max_length=50, null=True),
        ),
    ]
