# Generated by Django 6.0.8 on 2026-09-25 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0011_resident_philsys_id_number_resident_philsys_id_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='primary_color',
            field=models.CharField(default='#082B66', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color in #RRGGBB format.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
