# Generated by Django 6.0.8 on 2026-10-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0012_barangay_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='privacy_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='privacy_consent_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
