# Generated by Django 6.0.8 on 2026-10-08 18:42

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.db.models import Q


SEEDED_ACCOUNT_IDENTITIES = (
    ("admin_dupay", "captain.dupay@gridy.local"),
    ("tanod_dupay", "tanod.dupay@gridy.local"),
    ("resident_dupay", "resident.dupay@gridy.local"),
    ("admin_daungan", "captain.daungan@gridy.local"),
    ("resident_daungan", "resident.daungan@gridy.local"),
    ("dilg_admin", "dilg.admin@gridy.local"),
    ("admin_captain", "captain.delacruz@gridy.local"),
    ("field_tanod", "tanod.pedro@gridy.local"),
    ("resident_juan", "juan.delacruz@gridy.local"),
)


def revoke_seeded_demo_passwords(apps, schema_editor):
    User = apps.get_model("gridy_auth", "User")
    seeded_accounts = Q(username__in=[])
    for username, email in SEEDED_ACCOUNT_IDENTITIES:
        seeded_accounts |= Q(username=username, email=email)

    User.objects.using(schema_editor.connection.alias).filter(
        seeded_accounts,
    ).update(password=make_password(None))


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0013_resident_privacy_consent_at_and_more'),
    ]

    operations = [
        migrations.RunPython(
            revoke_seeded_demo_passwords,
            migrations.RunPython.noop,
        ),
    ]
