# Generated by Django 6.0.8 on 2026-10-09 01:17

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0014_revoke_seeded_demo_passwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=120)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_position', models.CharField(max_length=120)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=12)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='barangay',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='barangay',
            name='province',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='barangay',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('municipality'), django.db.models.functions.text.Lower('province'), condition=models.Q(models.Q(('municipality', ''), _negated=True), models.Q(('province', ''), _negated=True)), name='unique_barangay_locality'),
        ),
        migrations.AddField(
            model_name='barangayapplication',
            name='created_barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_application', to='gridy_auth.barangay'),
        ),
        migrations.AddField(
            model_name='barangayapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_barangay_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='barangayapplication',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('municipality'), django.db.models.functions.text.Lower('province'), condition=models.Q(('status', 'PENDING')), name='unique_pending_barangay_application'),
        ),
    ]
