[pytest]
DJANGO_SETTINGS_MODULE = config.settings
<<<<<<< HEAD
python_files = tests.py test_*.py *_tests.py
=======
addopts = -v
>>>>>>> 0a5592e (docs(core): update readme and env with latest features and configurations)
