# Generated by Django 6.0.7 on 2026-08-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('DOCUMENT_ACTION', 'Document Request Action'), ('QUEUE_ACTION', 'Queue Ticket Action'), ('REPORT_ACTION', 'Incident Report Action'), ('USER_ACTION', 'User Verification Action')], max_length=20),
        ),
    ]
