# Generated by Django 6.0.7 on 2026-07-31 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['user', 'status'], name='gridy_servi_user_id_f14409_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['status'], name='gridy_servi_status_f473b0_idx'),
        ),
        migrations.AddIndex(
            model_name='queueticket',
            index=models.Index(fields=['status', 'created_at'], name='gridy_servi_status_bcf00e_idx'),
        ),
        migrations.AddIndex(
            model_name='queueticket',
            index=models.Index(fields=['created_at'], name='gridy_servi_created_a84edc_idx'),
        ),
    ]
