# Generated by Django 6.0.7 on 2026-08-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_services', '0002_documentrequest_gridy_servi_user_id_f14409_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueticket',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueticket',
            name='priority_status',
            field=models.CharField(choices=[('regular', 'Regular'), ('priority', 'Priority/Senior/PWD/Pregnant')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='queueticket',
            name='walkin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
