# Generated by Django 6.0.7 on 2026-08-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_services', '0003_queueticket_notes_queueticket_priority_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('REJECTED', 'Rejected'), ('RELEASED', 'Released')], default='PENDING', max_length=20),
        ),
    ]
