# Generated by Django 6.0.7 on 2026-08-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_services', '0004_alter_documentrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueticket',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
