# Generated by Django 6.0.7 on 2026-08-23 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0006_barangay_alter_user_role_user_barangay'),
        ('gridy_services', '0005_queueticket_is_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueticket',
            name='barangay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_tickets', to='gridy_auth.barangay'),
        ),
    ]
