# Generated by Django 6.0.7 on 2026-08-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_services', '0006_queueticket_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('Barangay Clearance', 'Barangay Clearance'), ('Certificate of IndigencyCertificate of Indigency', 'Indigency'), ('Business PermitBusiness Permit', 'Business Permit'), ('Proof of Residency', 'Proof of Residency'), ('Barangay ID', 'Barangay ID'), ('Certificate of Good Moral Character', 'Certificate of Good Moral Character'), ('Certificate of Late Registration', 'Certificate of Late Registration'), ('Certificate of Solo Parent', 'Certificate of Solo Parent'), ('Certificate of Cohabitation', 'Certificate of Cohabitation'), ('First Time Job Seeker Certificate', 'First Time Job Seeker Certificate'), ('Certificate of No Property', 'Certificate of No Property'), ('Barangay Protection Order', 'Barangay Protection Order')], max_length=100),
        ),
    ]
