# Generated by Django 6.0.7 on 2026-08-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_services', '0007_alter_documentrequest_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(max_length=100),
        ),
    ]
