# Generated by Django 6.0.8 on 2026-09-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_services', '0008_alter_documentrequest_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
