# Generated by Django 6.0.8 on 2026-10-08 18:43

from django.db import migrations, models


def initialize_existing_payment_status(apps, schema_editor):
    DocumentRequest = apps.get_model("gridy_services", "DocumentRequest")
    requests = DocumentRequest.objects.using(schema_editor.connection.alias).filter(
        fee_amount__gt=0,
    )
    requests.exclude(or_number__isnull=True).exclude(or_number="").update(
        payment_method="CASH",
        payment_status="VERIFIED",
    )
    requests.filter(or_number__isnull=True).update(payment_status="UNPAID")
    requests.filter(or_number="").update(payment_status="UNPAID")


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_services', '0010_documentrequest_barangay_documentrequest_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('GCASH', 'GCash')], max_length=10),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('UNPAID', 'Unpaid'), ('PENDING_VERIFICATION', 'Pending verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', max_length=25),
        ),
        migrations.RunPython(
            initialize_existing_payment_status,
            migrations.RunPython.noop,
        ),
    ]
