# Generated by Django 6.0.8 on 2026-10-08 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0014_revoke_seeded_demo_passwords'),
        ('gridy_services', '0011_document_payment_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AidRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance_type', models.CharField(max_length=100)),
                ('reason', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('staff_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_requests', to='gridy_auth.barangay')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_aid_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['barangay', 'status', 'created_at'], name='gridy_servi_baranga_da6a50_idx'), models.Index(fields=['requester', 'created_at'], name='gridy_servi_request_c153db_idx')],
            },
        ),
    ]
