# Generated by Django 6.0.8 on 2026-10-08 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0013_resident_privacy_consent_at_and_more'),
        ('gridy_services', '0012_resident_aid_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='queueticket',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='queueticket',
            index=models.Index(fields=['barangay', 'called_at'], name='gridy_queue_call_idx'),
        ),
    ]
