# Generated by Django 6.0.8 on 2026-10-09 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_auth', '0015_barangayapplication_barangay_municipality_and_more'),
        ('gridy_services', '0013_queueticket_called_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='payment_instructions_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment_recipient_identifier_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment_recipient_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('MAYA', 'Maya'), ('BANK', 'Bank transfer'), ('OTHER', 'Other')], max_length=12),
        ),
        migrations.CreateModel(
            name='PaymentRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GCASH', 'GCash'), ('MAYA', 'Maya'), ('BANK', 'Bank transfer'), ('OTHER', 'Other')], max_length=16)),
                ('display_name', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_identifier', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_recipients', to='gridy_auth.barangay')),
            ],
            options={
                'ordering': ['provider', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests', to='gridy_services.paymentrecipient'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecipient',
            constraint=models.UniqueConstraint(fields=('barangay', 'provider', 'display_name'), name='unique_payment_recipient_per_barangay'),
        ),
    ]
