# Generated by Django 6.0.7 on 2026-07-31 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_communications', '0002_fcmdevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_pinned', 'created_at'], name='gridy_commu_is_pinn_6bc1f3_idx'),
        ),
    ]
