// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRi-M_iQ8XlxA4gAVculS2JefzPrit1tw',
    appId: '1:1087918076211:web:e2d084ad4c91bd14838e46',
    messagingSenderId: '1087918076211',
    projectId: 'device-streaming-aca41bd3',
    authDomain: 'device-streaming-aca41bd3.firebaseapp.com',
    storageBucket: 'device-streaming-aca41bd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOp0G27LV7z3A0lYogPRNlpWx0g8f5Rlg',
    appId: '1:1087918076211:android:57fffb2574d51134838e46',
    messagingSenderId: '1087918076211',
    projectId: 'device-streaming-aca41bd3',
    storageBucket: 'device-streaming-aca41bd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgwRDsxZK7WcaoTm4PvCewXBE7ct8E74E',
    appId: '1:1087918076211:ios:24c3140b4e7673ef838e46',
    messagingSenderId: '1087918076211',
    projectId: 'device-streaming-aca41bd3',
    storageBucket: 'device-streaming-aca41bd3.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgwRDsxZK7WcaoTm4PvCewXBE7ct8E74E',
    appId: '1:1087918076211:ios:24c3140b4e7673ef838e46',
    messagingSenderId: '1087918076211',
    projectId: 'device-streaming-aca41bd3',
    storageBucket: 'device-streaming-aca41bd3.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRi-M_iQ8XlxA4gAVculS2JefzPrit1tw',
    appId: '1:1087918076211:web:7e205cc6714ee17b838e46',
    messagingSenderId: '1087918076211',
    projectId: 'device-streaming-aca41bd3',
    authDomain: 'device-streaming-aca41bd3.firebaseapp.com',
    storageBucket: 'device-streaming-aca41bd3.firebasestorage.app',
  );
}
