# Generated by Django 6.0.7 on 2026-07-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='urgency',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='LOW', max_length=10),
        ),
    ]
