# Generated by Django 6.0.7 on 2026-08-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_reports', '0002_issuereport_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='urgency',
            field=models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('HAZARD', 'Hazard'), ('EMERGENCY', 'Emergency')], default='MINOR', max_length=20),
        ),
    ]
