# Generated by Django 6.0.7 on 2026-08-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridy_reports', '0003_alter_issuereport_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='category',
            field=models.CharField(choices=[('PEACE_AND_ORDER', 'Peace & Order (Riots, Noise, Curfew)'), ('PUBLIC_HEALTH', 'Public Health (Vaccinations, Medical)'), ('INFRASTRUCTURE', 'Infrastructure (Potholes, Outages)'), ('ENVIRONMENT', 'Environment (Floods, Waste)'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='incident_datetime',
            field=models.DateTimeField(blank=True, help_text='Exact time the scenario occurred.', null=True),
        ),
    ]
